include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/l10n"
    - "**/*.g.dart"
    - "lib/generated/**"
    - "**/*.freezed.dart"
linter:
  rules:
    sort_pub_dependencies: true
    lines_longer_than_80_chars: false

formatting:
  line_length: 170