name: the_classic_movies_app

packages:
  - .
  - modules/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  tests:
    run: melos exec --dir-exists=test --fail-fast -- \
      flutter test --no-pub -r github --dart-define=RUNNING_ON_CI=true
    description: Run all tests

  test:ask:
    run: melos exec --fail-fast -c 1 -- \
      flutter test --no-pub -r github
    description: Prompts to select the package to test.
    packageFilters:
      flutter: true
      dirExists: test

  update-golden:
    run: rm -rf **/test/golden_test/failures |
      rm -rf **/coverage |
      melos exec -- "fvm flutter test --test-randomize-ordering-seed random --update-goldens --tags=golden --coverage"
    packageFilters:
      flutter: true
      dirExists: test

  lint:
    run: melos exec -- "fvm flutter analyze"

  l10n:
    run: melos exec --dir-exists=test -c 1 -- \
      flutter gen-l10n
    packageFilters:
      flutter: true
      fileExists: l10n.yaml
