name: the_classic_movies_app_example
description: "A Flutter application for classic movies."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  core:
    path: modules/core
  cupertino_icons: ^1.0.6
  design_system:
    path: modules/design_system
  firebase_core: ^3.13.0
  firebase_remote_config: ^5.4.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.2.0
  intl: ^0.19.0
  movies:
    path: modules/movies

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  melos: ^6.3.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Regular.ttf
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/Gilroy-Heavy.ttf
          weight: 600

flutter_intl:
  generate: true