name: the_classic_movies_app_example
description: "A Flutter application for classic movies."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  design_system:
    path: modules/design_system
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.2.0
  intl: ^0.19.0
  movies:
    path: modules/movies

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  melos: ^6.3.2

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  generate: true
