// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:core/env.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static final Env _env = Env();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _env.firebaseWebApiKey,
    appId: _env.firebaseWebAppId,
    messagingSenderId: _env.firebaseMessagingSenderId,
    projectId: _env.firebaseProjectId,
    authDomain: _env.firebaseAuthDomain,
    storageBucket: _env.firebaseStorageBucket,
    measurementId: _env.firebaseMeasurementId,
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _env.firebaseAndroidApiKey,
    appId: _env.firebaseAndroidAppId,
    messagingSenderId: _env.firebaseMessagingSenderId,
    projectId: _env.firebaseProjectId,
    storageBucket: _env.firebaseStorageBucket,
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _env.firebaseIosApiKey,
    appId: _env.firebaseIosAppId,
    messagingSenderId: _env.firebaseMessagingSenderId,
    projectId: _env.firebaseProjectId,
    storageBucket: _env.firebaseStorageBucket,
    iosBundleId: _env.firebaseIosBundleId,
  );
}