name: movies
description: "Movies module for the classic movies app."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core
  design_system:
    path: ../design_system
  dio: ^5.4.0
  firebase_remote_config: ^5.4.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  provider: ^6.1.1
  sentry_dio: ^8.14.2
  sentry_flutter: ^8.14.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  hive_generator: ^2.0.1
  mocktail: ^1.0.4

flutter:
  generate: true
