name: dev

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: kuhnroyal/flutter-fvm-config-action/setup@v3
        with:
          cache: true
          pub-cache: true

      - name: Install FVM
        run: |
          dart pub global activate fvm
          echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"

      - name: Warm FVM cache
        run: |
          fvm install --setup --skip-pub-get
          fvm dart pub global activate melos

      - name: Bootstrap packages
        run: melos bootstrap

      - name: Setup Firebase Configuration
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 --decode > ios/Runner/GoogleService-Info.plist
          echo "${{ secrets.FIREBASE_JSON }}" | base64 --decode > firebase.json

      - name: Lint
        run: melos lint

      - name: Unit tests
        env:
          RUNNING_ON_CICD: true
        run: melos tests

      - name: Build Web
        run: flutter build web $DART_DEFINE_ARGS
        env:
          DART_DEFINE_ARGS: >-
            --dart-define=TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}
            --dart-define=TMDB_BASE_URL=${{ secrets.TMDB_BASE_URL }}
            --dart-define=TMDB_IMAGE_URL=${{ secrets.TMDB_IMAGE_URL }}
            --dart-define=FIREBASE_WEB_API_KEY=${{ secrets.FIREBASE_WEB_API_KEY }}
            --dart-define=FIREBASE_WEB_APP_ID=${{ secrets.FIREBASE_WEB_APP_ID }}
            --dart-define=FIREBASE_ANDROID_API_KEY=${{ secrets.FIREBASE_ANDROID_API_KEY }}
            --dart-define=FIREBASE_ANDROID_APP_ID=${{ secrets.FIREBASE_ANDROID_APP_ID }}
            --dart-define=FIREBASE_IOS_API_KEY=${{ secrets.FIREBASE_IOS_API_KEY }}
            --dart-define=FIREBASE_IOS_APP_ID=${{ secrets.FIREBASE_IOS_APP_ID }}
            --dart-define=FIREBASE_IOS_BUNDLE_ID=${{ secrets.FIREBASE_IOS_BUNDLE_ID }}
            --dart-define=FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
            --dart-define=FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
            --dart-define=FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
            --dart-define=FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}
            --dart-define=FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{secrets.FIREBASE_SERVICE_ACCOUNT_THE_CLASSIC_MOVIES_APP_EXAMPLE }}
          channelId: live
          projectId: the-classic-movies-app-example
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks