name: dev

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: kuhnroyal/flutter-fvm-config-action/setup@v3
        with:
          cache: true
          pub-cache: true

      - name: Install FVM
        run: |
          dart pub global activate fvm
          echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"

      - name: Warm FVM cache
        run: |
          fvm install --setup --skip-pub-get
          fvm dart pub global activate melos

      - name: Bootstrap packages
        run: melos bootstrap

      - name: Setup Environment Variables
        run: |
          echo "TMDB_API_KEY=$TMDB_API_KEY" > .env
          echo "TMDB_BASE_URL=$TMDB_BASE_URL" >> .env
          echo "TMDB_IMAGE_URL=$TMDB_IMAGE_URL" >> .env
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TMDB_BASE_URL: https://api.themoviedb.org/3
          TMDB_IMAGE_URL: https://image.tmdb.org/t/p/

      - name: Lint
        run: melos lint

      - name: Unit tests
        env:
          RUNNING_ON_CICD: true
        run: melos tests