name: dev

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: "stable"

      - name: Pub get
        run: flutter pub get

      - name: Lint
        run: flutter analyze

      - name: Unit Test
        run: flutter test
        env:
          RUNNING_ON_CICD: true